### ISSUE TITLE
New Callsign not returning info

### ISSUE THREAD

**Issue by k5dvt** [ae5au/gmrs.app-website#25]
Looked up callsign WSAC493 which was granted on 1/05/2024 but it doesn't show up on gmrs.app. Older callsigns such as mine (WRKG942) do resolve. Is the database from the FCC not updating? It's been a while since this call has been issued so I figured it would work it's way through a database update.

THANK YOU FOR THE SITE LUKE!

Jon "I wish I could be of more help on the problem" Williams

**Comment by ae5au** [comment]
@k5dvt it looks up for me and even returns another result with the same address:
![image](https://github.com/ae5au/gmrs.app-website/assets/5542863/679db308-0e73-4cd1-9caf-53fe46c081a9)

**Comment by ae5au** [comment]
Also, FYI, I update the database weekly on early AM Monday our time using the weekly full files from the FCC. I don't bother to try to merge in each daily delta that they put out throughout the week

**Comment by k5dvt** [comment]
I wish I had a screen shot, but I noticed when I entered in the callsign it
would stay lower case and the results just would never pop up. That's very
odd. I've tried both lowercase and entering it as upper case and now get
the result. Well, sorry for the inconvenience!

**Comment by ae5au** [comment]
Strange. I'm going to close this for now, but please let me know if you see it again.
